---
title: "Assignment"
format:
  html:
    embed-resources: true
editor: visual
---

# **Group 11 and 26**

## **Names:**

Joachim (s254717)

Dario (s253692)

Sotirios (s253723)

Antonios (s253722)

Bertram (s206178)

# Assignment

## Background

PCA is very useful and we are now gonna learn it to be smart :). We will go through different uses of PCA in R.

## load dependencies

```{r}
library(tidyverse)
library(MASS)
library(broom)
library(cowplot)

```

## load data

```{r}

str(biopsy)

head(biopsy)

<<<<<<< HEAD
=======

>>>>>>> da7c4165069b121a3a0919c8012845084d7f30e5
```

```{r}
pca_fit <- biopsy %>% 
  na.omit() |> 
  dplyr::select(where(is.numeric)) %>% # retain only numeric columns¨
  scale() %>% # scale data
  prcomp(scale = TRUE) # do PCA on scaled data
```

## replicating part 2

```{r}
# extract rotation matrix
pca_fit %>%
  tidy(matrix = "rotation")
```

```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + # fix aspect ratio to 1:1
  theme_minimal_grid(12)
```

## replicating part 3

```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```

## conclusion

We can now collaborate and do PCA, Yayy!
